# Generated by Django 5.2.4 on 2026-05-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='serached_at',
            new_name='searched_at',
        ),
    ]
